eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
server:
  port: 9001
spring:
  application:
    name: service-login
  mvc:
    static-path-pattern: /**
    view:
      prefix: /
      suffix: .html
  resources:
    static-locations: classpath:templates,classpath:css,classpath:js,classpath:image